### ISSUE TITLE
Show build status

### ISSUE THREAD

**Issue by jernejk** [panuoksala/streamdeck-azuredevops-plugin#1]
Hi, I love the idea of the project but I would love to see the status of the project.

I have quickly hacked away a version where instead of running builds (not helpful as they start automatically) and instead track them.

![image](https://user-images.githubusercontent.com/5943653/138816937-c929b427-066d-4488-8462-a917f9e89bd9.png)
**Figure:** Updating every minute.

![image](https://user-images.githubusercontent.com/5943653/138816883-6dc82358-18b1-4fdf-b340-673a8a0d089b.png)
**Figure:** Build in progress.

I'll make a PR once I can replicate the old behavior and add new one.
The idea is following:

Configuration (in addition to current):
* Display: **Build** | **Release**
* Tap action: **Refresh status** | **start build/release** | **open build/release in browser**
* Long press: same as above
* Show project name: **Top** | **Bottom** | **Azure icon**

Display:
* Status - Changing icons instead of text
* Loading animation when fetching data/executing actions

Current work in progress:
https://github.com/jernejk/streamdeck-azuredevops-plugin

**Comment by panuoksala** [comment]
That sounds really good improvement. Should the polling interval be a setting maybe, with 60 second default if build has been triggered?

**Comment by jernejk** [comment]
Hi, some new update on the progress.

I added new icons for builds.
![image](https://user-images.githubusercontent.com/5943653/140746573-686a56ed-7473-4364-a51f-1fd98456a76e.png)

Here are more icons.
![image](https://user-images.githubusercontent.com/5943653/140746794-dbceb7ec-e054-4927-b2a8-288865b9d2f3.png)

The colors were picked from Azure DevOps while the icons inside are text, emojis, or simple shapes.
Probably should have a designer touch for this. :)

There are a few things missing:
1. Add new settings
2. Release status
3. Long press action

For "In progress" atm will only work for the last 24 hours because build/release pending approval is not easy to get via REST APIs.

**Comment by panuoksala** [comment]
I think that should be fine. The Microsoft had some restrictions about the icons (which I asked permission of course) and I think those progress icons on top right corner would not break those.

**Comment by jernejk** [comment]
The code is done now but probably should be tested against various projects.

It is a bit of a breaking change as the tap action is now refreshing the status instead of starting a build/release.
This can be changed as tap and long-press actions are configurable.

**Comment by panuoksala** [comment]
OK looks cool, I will test it out during the weekend.

**Comment by jernejk** [comment]
Next PR I'll likely add an additional action to open the build/release in the browser.

In case of the build where we can't approve via API, it's beneficial we can open them via StreamDeck.

**Comment by panuoksala** [comment]
Released in version 1.1.0
