### ISSUE TITLE
The resource cannot be found.

### ISSUE THREAD

**Issue by myMartek** [panuoksala/streamdeck-azuredevops-plugin#13]
I tried your plugin. Unfortunatly I was not able to get it working.

I am pretty sure I added the correct setting values, but when I try to get the status I only get the error "The resource cannot be found."

Is there anything else I can do in order to find out why its not working?

**Comment by bmacombe** [comment]
I installed it today and I'm having the same issue

**Comment by panuoksala** [comment]
Could you check the %AppData%\Roaming\Elgato\StreamDeck\Plugins\net.oksala.azuredevops.runner.DefaultPlugi.sdPlugin\log folder. There should be log file.

**Comment by panuoksala** [comment]
The resource cannot be found sounds a lot like issue with images in the plugin, but maybe the log contains more info.

**Comment by myMartek** [comment]
Actually the logs do not show any errors.

But: I created a new button today and it now "magically" works.
Seems like a temporary bug or something.

I did not enter anything different then last time

**Comment by bmacombe** [comment]
I tried recreating one today and still get the resource error. I don't see any errors in my log either.
[azuredevopsplugin20220316.log](https://github.com/panuoksala/streamdeck-azuredevops-plugin/files/8263871/azuredevopsplugin20220316.log)

**Comment by bmacombe** [comment]
I created a new button with no config and get the same error

**Comment by panuoksala** [comment]
I will send new version into Elgato during the weekend (maybe tomorrow) so it should arrive into shop pretty soon.

**Comment by bmacombe** [comment]
I'll give it another try next week or feel free to ping me when it's available. Glad to help however I can.

Thanks!

**Comment by panuoksala** [comment]
Submitted version 1.2.0 to Elgato which has improved logging. I will inform when the update is available at store. Usually it does not take long.

**Comment by panuoksala** [comment]
Version 1.2.0 is now available at the store. Please try again with that.

**Comment by bmacombe** [comment]
I can confirm it's working for me now. Thanks!
