### ISSUE TITLE
status icon size

### ISSUE THREAD

**Issue by paulsaitta** [panuoksala/streamdeck-azuredevops-plugin#48]
can you make the status icon bigger or make it the background.  the status for a release comes up as a small circle in the right cor
ner and its hard to tell what the status is being as small as it is.
![2024-05-22_14-27-46](https://github.com/panuoksala/streamdeck-azuredevops-plugin/assets/150190519/3822a767-f7b0-4b04-a2d4-c89f304e8ac8)

**Comment by panuoksala** [comment]
I think the background would be cool, but the images would require bit of tweaking.. I will check that out and if it is not easy to do, I will increase the icon size.

**Comment by panuoksala** [comment]
New icon Size:
![image](https://github.com/panuoksala/streamdeck-azuredevops-plugin/assets/15687235/6bdbba19-c1e7-422a-9e96-0311b2040354)

**Comment by panuoksala** [comment]
Update icon:
![image](https://github.com/panuoksala/streamdeck-azuredevops-plugin/assets/15687235/829683e7-ad36-4376-9196-f396f6bf7c8f)

**Comment by paulsaitta** [comment]
thanks
